
name: tubehub
services:
  tubehub:
    build: .
    ports:
      - "5174:3000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - CLEANUP_THRESHOLD_HOURS=${CLEANUP_THRESHOLD_HOURS:-24}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-60}
    restart: unless-stopped
